name: photos
favicon: null
layout_spectrum: 0.57297
typography_spectrum: 0.41622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6b6d8b'
    - '#762325'
    - '#ffffff'
    - '#ee9b58'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
