name: photos
favicon: null
layout_spectrum: 0.57981
typography_spectrum: 0.41622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbb8b1'
    - '#8b8784'
    - '#595758'
    - '#00140b'
    - '#f2e2c7'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: shares
    item: null
    url: null
